from django.urls import path

from .views import auctions, pool, pools, search, stats, token, tokens

urlpatterns = [
    path(
        "pools/",
        pools.PoolsView.as_view(),
        name="pools",
    ),
    path(
        "pools/<pool_address>/",
        pool.PoolView.as_view(),
        name="pool",
    ),
    path(
        "pools/<pool_address>/buckets/",
        pool.BucketsView.as_view(),
        name="pool-buckets",
    ),
    path(
        "pools/<pool_address>/buckets/graph/",
        pool.BucketsGraphView.as_view(),
        name="pool-buckets-graph",
    ),
    path(
        "pools/<pool_address>/historic/<historic_type>/",
        pool.PoolHistoricView.as_view(),
        name="pool-historic",
    ),
    path(
        "pools/<pool_address>/events/",
        pool.PoolEventsView.as_view(),
        name="pool-events",
    ),
    path(
        "pools/<pool_address>/borrowers/",
        pool.PoolBorrowersView.as_view(),
        name="pool-borrowers",
    ),
    path(
        "tokens/",
        tokens.TokensView.as_view(),
        name="tokens",
    ),
    path(
        "tokens/<underlying_address>/",
        token.TokenView.as_view(),
        name="token",
    ),
    path(
        "tokens/<underlying_address>/overview/",
        token.TokenOverviewView.as_view(),
        name="token-overview",
    ),
    path(
        "tokens/<underlying_address>/pools/",
        token.TokenPoolsView.as_view(),
        name="token-pools",
    ),
    path(
        "tokens/<underlying_address>/arbitrage-pools/",
        token.TokenArbitragePoolsView.as_view(),
        name="token-arbitrage-pools",
    ),
    path(
        "stats/overview/",
        stats.OverviewView.as_view(),
        name="overview",
    ),
    path(
        "search/",
        search.SearchView.as_view(),
        name="search",
    ),
    path(
        "auctions/settled/",
        auctions.AuctionsSettledView.as_view(),
        name="auctions-settled",
    ),
    path(
        "auctions/settled/overview/",
        auctions.AuctionsSettledOverviewView.as_view(),
        name="auctions-settled-overview",
    ),
    path(
        "auctions/settled/graphs/<graph_type>/",
        auctions.AuctionsSettledGraphsView.as_view(),
        name="auctions-settled-graphs",
    ),
    path(
        "auctions/active/",
        auctions.AuctionsActiveView.as_view(),
        name="auctions-active",
    ),
]
