version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/setup-poetry-env/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "blockanalitica/code-reviewers"
    labels:
      - "dependencies"
    groups:
      python:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
