repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.4
      hooks:
        - id: ruff
          exclude: .*/migrations/.*
          language_version: python3.11
        - id: ruff-format
          args: [--check]
          exclude: .*/migrations/.*
          language_version: python3.11
