repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude .
        language: system
        types: [python]
        require_serial: true
        extend-exclude: '.*/migrations/.*'

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude . --check
        language: system
        types: [python]
        require_serial: true
        extend-exclude: '.*/migrations/.*'
