[tool.poetry]
description = "Ajna API service"
authors = []
license = "AGPL"
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = "^3.11"
boto3 = "1.34.25"
celery = "5.3.6"
chain-harvester = "0.23.1"
django-autoslug = "1.9.9"
django-bulk-load = "1.4.3"
django-celery-beat = "2.5.0"
django-cors-headers = "4.3.1"
django-environ = "0.11.2"
django-extensions = "3.2.3"
django-model-utils = "4.3.1"
django-redis = "5.4.0"
django = "4.2.9"
djangorestframework = "3.14.0"
eth-abi = "4.2.1"
gunicorn = "21.2.0"
hexbytes = "0.3.1"
hiredis = "2.3.2"
ijson = "3.2.3"
ipython = "8.20.0"
psycopg2 = "2.9.9"
pyopenssl = "23.3.0"
redis = "5.0.1"
requests = "2.31.0"
sentry-sdk = "1.39.2"
statsd = "4.0.1"
web3 = "6.13.0"
werkzeug = "3.0.1"
whitenoise = "6.6.0"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "4.2.0"
factory-boy = "3.3.0"
freezegun = "1.4.0"
pytest-django = "4.7.0"
pytest-mock = "3.12.0"
pytest-sugar = "0.9.7"
pytest = "7.4.4"
responses = "0.24.1"
black = "23.12.1"
flake8-bugbear = "24.1.17"
flake8-comprehensions = "3.14.0"
flake8-isort = "6.1.1"
flake8-print = "5.0.0"
flake8 = "7.0.0"
isort = "5.13.2"
pre-commit = "3.6.0"

[tool.black]
target-version = ["py310"]
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | .data
  | .venv
)/
'''
skip-numeric-underscore-normalization = true


[tool.isort]
profile = "black"
skip_glob=["*/migrations/*", ".venv/*"]


[tool.pytest.ini_options]
addopts = "--ds=config.settings.test --no-migrations --capture=no --verbose"


