# Generated by Django 4.1.7 on 2023-05-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0002_v1ethereumpricefeed_v1goerlipricefeed"),
    ]

    operations = [
        migrations.CreateModel(
            name="V1GoerliRemoveCollateral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("bucket_index", models.BigIntegerField()),
                ("claimer", models.CharField(max_length=42)),
                ("index", models.BigIntegerField()),
                ("amount", models.DecimalField(decimal_places=18, max_digits=32)),
                ("lp_redeemed", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_timestamp", models.BigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    ("pool_address", "bucket_index", "claimer", "transaction_hash")
                },
            },
        ),
        migrations.CreateModel(
            name="V1EthereumRemoveCollateral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("bucket_index", models.BigIntegerField()),
                ("claimer", models.CharField(max_length=42)),
                ("index", models.BigIntegerField()),
                ("amount", models.DecimalField(decimal_places=18, max_digits=32)),
                ("lp_redeemed", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_timestamp", models.BigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    ("pool_address", "bucket_index", "claimer", "transaction_hash")
                },
            },
        ),
    ]
