# Generated by Django 4.1.7 on 2023-05-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0003_v1goerliremovecollateral_v1ethereumremovecollateral"),
    ]

    operations = [
        migrations.CreateModel(
            name="V1GoerliAddCollateral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("bucket_index", models.BigIntegerField()),
                ("actor", models.CharField(max_length=42)),
                ("index", models.BigIntegerField()),
                ("amount", models.DecimalField(decimal_places=18, max_digits=32)),
                ("lp_awarded", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_timestamp", models.BigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    (
                        "pool_address",
                        "bucket_index",
                        "actor",
                        "index",
                        "transaction_hash",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="V1EthereumAddCollateral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("bucket_index", models.BigIntegerField()),
                ("actor", models.CharField(max_length=42)),
                ("index", models.BigIntegerField()),
                ("amount", models.DecimalField(decimal_places=18, max_digits=32)),
                ("lp_awarded", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_timestamp", models.BigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    (
                        "pool_address",
                        "bucket_index",
                        "actor",
                        "index",
                        "transaction_hash",
                    )
                },
            },
        ),
    ]
