# Generated by Django 4.1.7 on 2023-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0008_v1goerlirepaydebt_v1ethereumrepaydebt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="v1ethereumpool",
            old_name="interest_rate",
            new_name="borrow_rate",
        ),
        migrations.RenameField(
            model_name="v1ethereumpool",
            old_name="current_debt",
            new_name="debt",
        ),
        migrations.RenameField(
            model_name="v1ethereumpoolsnapshot",
            old_name="interest_rate",
            new_name="borrow_rate",
        ),
        migrations.RenameField(
            model_name="v1ethereumpoolsnapshot",
            old_name="current_debt",
            new_name="debt",
        ),
        migrations.RenameField(
            model_name="v1goerlipool",
            old_name="interest_rate",
            new_name="borrow_rate",
        ),
        migrations.RenameField(
            model_name="v1goerlipool",
            old_name="current_debt",
            new_name="debt",
        ),
        migrations.RenameField(
            model_name="v1goerlipoolsnapshot",
            old_name="interest_rate",
            new_name="borrow_rate",
        ),
        migrations.RenameField(
            model_name="v1goerlipoolsnapshot",
            old_name="current_debt",
            new_name="debt",
        ),
        migrations.RemoveField(
            model_name="v1ethereumpool",
            name="inflator_update",
        ),
        migrations.RemoveField(
            model_name="v1ethereumpool",
            name="pending_inflator",
        ),
        migrations.RemoveField(
            model_name="v1ethereumpool",
            name="pending_interest_factor",
        ),
        migrations.RemoveField(
            model_name="v1ethereumpoolsnapshot",
            name="inflator_update",
        ),
        migrations.RemoveField(
            model_name="v1ethereumpoolsnapshot",
            name="pending_inflator",
        ),
        migrations.RemoveField(
            model_name="v1ethereumpoolsnapshot",
            name="pending_interest_factor",
        ),
        migrations.RemoveField(
            model_name="v1goerlipool",
            name="inflator_update",
        ),
        migrations.RemoveField(
            model_name="v1goerlipool",
            name="pending_inflator",
        ),
        migrations.RemoveField(
            model_name="v1goerlipool",
            name="pending_interest_factor",
        ),
        migrations.RemoveField(
            model_name="v1goerlipoolsnapshot",
            name="inflator_update",
        ),
        migrations.RemoveField(
            model_name="v1goerlipoolsnapshot",
            name="pending_inflator",
        ),
        migrations.RemoveField(
            model_name="v1goerlipoolsnapshot",
            name="pending_interest_factor",
        ),
        migrations.AddField(
            model_name="v1ethereumbucket",
            name="bucket_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpool",
            name="collateral_token_balance",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpool",
            name="quote_token_balance",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpool",
            name="t0debt",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="t0debt",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlibucket",
            name="bucket_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="collateral_token_balance",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="quote_token_balance",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="t0debt",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="t0debt",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
