# Generated by Django 4.1.7 on 2023-05-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0009_rename_interest_rate_v1ethereumpool_borrow_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="collateral_token_balance",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="quote_token_balance",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="collateral_token_balance",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="quote_token_balance",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
