# Generated by Django 4.1.7 on 2023-05-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0010_v1ethereumpoolsnapshot_collateral_token_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v1ethereumpoolsnapshot",
            name="address",
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name="v1goerlipoolsnapshot",
            name="address",
            field=models.CharField(db_index=True, max_length=42),
        ),
    ]
