# Generated by Django 4.1.7 on 2023-06-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0011_alter_v1ethereumpoolsnapshot_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V1GoerliLiquidationAuction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("settled", models.BooleanField()),
                ("settleTime", models.BigIntegerField()),
                ("datetime", models.DateTimeField()),
                ("neutralPrice", models.DecimalField(decimal_places=18, max_digits=32)),
                ("kicker", models.CharField(max_length=42)),
                ("kickTime", models.BigIntegerField()),
                ("debt", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "collateralRemaining",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("borrower", models.CharField(max_length=42)),
                ("bondSize", models.DecimalField(decimal_places=18, max_digits=32)),
                ("bondFactor", models.DecimalField(decimal_places=18, max_digits=32)),
                ("auctionPrice", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "debtRemaining",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
            ],
            options={
                "ordering": ("-datetime",),
                "get_latest_by": "datetime",
                "abstract": False,
            },
        ),
    ]
