# Generated by Django 4.1.7 on 2023-06-07 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0012_v1goerliliquidationauction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="v1goerliliquidationauction",
            old_name="auctionPrice",
            new_name="auction_price",
        ),
        migrations.RenameField(
            model_name="v1goerliliquidationauction",
            old_name="bondFactor",
            new_name="bond_factor",
        ),
        migrations.RenameField(
            model_name="v1goerliliquidationauction",
            old_name="bondSize",
            new_name="bond_size",
        ),
        migrations.RenameField(
            model_name="v1goerliliquidationauction",
            old_name="collateralRemaining",
            new_name="collateral_remaining",
        ),
        migrations.RenameField(
            model_name="v1goerliliquidationauction",
            old_name="debtRemaining",
            new_name="debt_remaining",
        ),
        migrations.RenameField(
            model_name="v1goerliliquidationauction",
            old_name="kickTime",
            new_name="kick_time",
        ),
        migrations.RenameField(
            model_name="v1goerliliquidationauction",
            old_name="neutralPrice",
            new_name="neutral_price",
        ),
        migrations.RenameField(
            model_name="v1goerliliquidationauction",
            old_name="settleTime",
            new_name="settle_time",
        ),
    ]
