# Generated by Django 4.2 on 2023-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ajna",
            "0013_rename_auctionprice_v1goerliliquidationauction_auction_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="collateral_token_address",
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="quote_token_address",
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="collateral_token_address",
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="quote_token_address",
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1ethereumpool",
            name="collateral_token_address",
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name="v1ethereumpool",
            name="quote_token_address",
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipool",
            name="collateral_token_address",
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipool",
            name="quote_token_address",
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
    ]
