# Generated by Django 4.1.7 on 2023-06-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0014_v1ethereumpoolsnapshot_collateral_token_address_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="v1ethereumdrawdebt",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="v1ethereumrepaydebt",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="v1goerlidrawdebt",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="v1goerlirepaydebt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="v1ethereumdrawdebt",
            name="index",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumrepaydebt",
            name="index",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlidrawdebt",
            name="index",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlirepaydebt",
            name="index",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="v1ethereumdrawdebt",
            unique_together={("index", "pool_address", "borrower", "transaction_hash")},
        ),
        migrations.AlterUniqueTogether(
            name="v1ethereumrepaydebt",
            unique_together={("index", "pool_address", "borrower", "transaction_hash")},
        ),
        migrations.AlterUniqueTogether(
            name="v1goerlidrawdebt",
            unique_together={("index", "pool_address", "borrower", "transaction_hash")},
        ),
        migrations.AlterUniqueTogether(
            name="v1goerlirepaydebt",
            unique_together={("index", "pool_address", "borrower", "transaction_hash")},
        ),
    ]
