# Generated by Django 4.1.7 on 2023-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0015_alter_v1ethereumdrawdebt_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1goerliliquidationauction",
            name="collateral_token_address",
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliliquidationauction",
            name="collateral_underlying_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliliquidationauction",
            name="debt_token_address",
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliliquidationauction",
            name="debt_underlying_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliliquidationauction",
            name="uid",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerliliquidationauction",
            name="settle_time",
            field=models.BigIntegerField(null=True),
        ),
    ]
