# Generated by Django 4.2.1 on 2023-06-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0017_v1ethereumaddcollateral_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpool",
            name="pending_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="pending_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="pending_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="pending_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
