# Generated by Django 4.2.1 on 2023-06-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0018_v1ethereumpool_pending_inflator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V1EthereumLiquidationAuction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=256, null=True)),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("settled", models.BooleanField()),
                ("settle_time", models.BigIntegerField(null=True)),
                ("datetime", models.DateTimeField()),
                (
                    "neutral_price",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("kicker", models.CharField(max_length=42)),
                ("kick_time", models.BigIntegerField()),
                ("debt", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "collateral_remaining",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("borrower", models.CharField(max_length=42)),
                ("bond_size", models.DecimalField(decimal_places=18, max_digits=32)),
                ("bond_factor", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "auction_price",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "debt_remaining",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "collateral_underlying_price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
                (
                    "debt_underlying_price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
                (
                    "collateral_token_address",
                    models.CharField(max_length=42, null=True),
                ),
                ("debt_token_address", models.CharField(max_length=42, null=True)),
            ],
            options={
                "ordering": ("-datetime",),
                "get_latest_by": "datetime",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V1GoerliPoolVolumeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=32)),
                ("date", models.DateField()),
            ],
            options={
                "abstract": False,
                "unique_together": {("pool_address", "date")},
            },
        ),
        migrations.CreateModel(
            name="V1EthereumPoolVolumeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=32)),
                ("date", models.DateField()),
            ],
            options={
                "abstract": False,
                "unique_together": {("pool_address", "date")},
            },
        ),
    ]
