# Generated by Django 4.2.1 on 2023-07-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0019_v1ethereumliquidationauction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="v1ethereumliquidationauction",
            name="auction_price",
        ),
        migrations.RemoveField(
            model_name="v1ethereumpool",
            name="fee_rate",
        ),
        migrations.RemoveField(
            model_name="v1ethereumpoolsnapshot",
            name="fee_rate",
        ),
        migrations.RemoveField(
            model_name="v1goerliliquidationauction",
            name="auction_price",
        ),
        migrations.RemoveField(
            model_name="v1goerlipool",
            name="fee_rate",
        ),
        migrations.RemoveField(
            model_name="v1goerlipoolsnapshot",
            name="fee_rate",
        ),
        migrations.AddField(
            model_name="v1ethereumaddquotetoken",
            name="bucket_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumaddquotetoken",
            name="deposit_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumaddquotetoken",
            name="fee",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumdrawdebt",
            name="borrow_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumliquidationauction",
            name="last_take_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpool",
            name="borrow_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpool",
            name="deposit_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="borrow_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="deposit_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliaddquotetoken",
            name="bucket_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliaddquotetoken",
            name="deposit_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliaddquotetoken",
            name="fee",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlidrawdebt",
            name="borrow_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliliquidationauction",
            name="last_take_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="borrow_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="deposit_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="borrow_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="deposit_fee_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
