# Generated by Django 4.2.1 on 2023-07-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0020_remove_v1ethereumliquidationauction_auction_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v1ethereumpool",
            name="collateralization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1ethereumpoolsnapshot",
            name="collateralization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipool",
            name="collateralization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipoolsnapshot",
            name="collateralization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
