# Generated by Django 4.2.3 on 2023-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0022_remove_v1ethereumpool_collateralization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumliquidationauction",
            name="wallet_address",
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliliquidationauction",
            name="wallet_address",
            field=models.CharField(max_length=42, null=True),
        ),
    ]
