# Generated by Django 4.2.3 on 2023-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0023_v1ethereumliquidationauction_wallet_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpool",
            name="utilization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="utilization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="utilization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="utilization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
