# Generated by Django 4.2.3 on 2023-07-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0024_v1ethereumpool_utilization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V1GoerliMoveQuoteToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("bucket_index_from", models.BigIntegerField()),
                ("bucket_index_to", models.BigIntegerField()),
                ("lender", models.CharField(max_length=42)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "lp_redeemed_from",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "lp_awarded_to",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("lup", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_timestamp", models.BigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                (
                    "price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    (
                        "pool_address",
                        "bucket_index_from",
                        "bucket_index_to",
                        "lender",
                        "transaction_hash",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="V1EthereumMoveQuoteToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("bucket_index_from", models.BigIntegerField()),
                ("bucket_index_to", models.BigIntegerField()),
                ("lender", models.CharField(max_length=42)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "lp_redeemed_from",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "lp_awarded_to",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("lup", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_timestamp", models.BigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                (
                    "price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    (
                        "pool_address",
                        "bucket_index_from",
                        "bucket_index_to",
                        "lender",
                        "transaction_hash",
                    )
                },
            },
        ),
    ]
