# Generated by Django 4.2.3 on 2023-08-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0026_v1ethereumgrantproposal_v1goerligrantproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
