# Generated by Django 4.2.3 on 2023-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0028_v2ethereumgrantproposal_v2ethereumliquidationauction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v1ethereumpool",
            name="total_bond_escrowed",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1ethereumpoolsnapshot",
            name="total_bond_escrowed",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipool",
            name="total_bond_escrowed",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipoolsnapshot",
            name="total_bond_escrowed",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpool",
            name="total_bond_escrowed",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpoolsnapshot",
            name="total_bond_escrowed",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipool",
            name="total_bond_escrowed",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipoolsnapshot",
            name="total_bond_escrowed",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
