# Generated by Django 4.2.3 on 2023-08-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0028_v1goerlicurrentwalletpoolposition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V1GoerliPoolEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("order_index", models.CharField(db_index=True, max_length=26)),
                ("transaction_hash", models.CharField(max_length=66)),
                ("name", models.CharField(db_index=True, max_length=42)),
                ("data", models.JSONField()),
                ("pool_inflator", models.DecimalField(decimal_places=18, max_digits=32)),
            ],
            options={
                "abstract": False,
                "unique_together": {("pool_address", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="V1EthereumPoolEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("order_index", models.CharField(db_index=True, max_length=26)),
                ("transaction_hash", models.CharField(max_length=66)),
                ("name", models.CharField(db_index=True, max_length=42)),
                ("data", models.JSONField()),
                ("pool_inflator", models.DecimalField(decimal_places=18, max_digits=32)),
            ],
            options={
                "abstract": False,
                "unique_together": {("pool_address", "order_index")},
            },
        ),
    ]
