# Generated by Django 4.2.3 on 2023-08-30 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0029_v1goerlipoolevent_v1ethereumpoolevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpoolevent",
            name="wallet_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=42), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="v1goerlipoolevent",
            name="wallet_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=42), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="v1ethereumpoolevent",
            name="name",
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name="v1ethereumpoolevent",
            name="order_index",
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name="v1ethereumpoolevent",
            name="pool_address",
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name="v1ethereumpoolevent",
            name="pool_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipoolevent",
            name="name",
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name="v1goerlipoolevent",
            name="order_index",
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name="v1goerlipoolevent",
            name="pool_address",
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name="v1goerlipoolevent",
            name="pool_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpoolevent",
            index=models.Index(
                fields=["pool_address", "order_index"],
                name="ajna_v1ethe_pool_ad_2bc1a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpoolevent",
            index=models.Index(
                fields=["pool_address", "wallet_addresses", "order_index"],
                name="ajna_v1ethe_pool_ad_9d997f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpoolevent",
            index=models.Index(
                fields=["pool_address", "wallet_addresses"],
                name="ajna_v1ethe_pool_ad_266415_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpoolevent",
            index=models.Index(
                fields=["pool_address"], name="ajna_v1ethe_pool_ad_dcbdb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpoolevent",
            index=models.Index(
                fields=["order_index"], name="ajna_v1ethe_order_i_3c27a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipoolevent",
            index=models.Index(
                fields=["pool_address", "order_index"],
                name="ajna_v1goer_pool_ad_d901a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipoolevent",
            index=models.Index(
                fields=["pool_address", "wallet_addresses", "order_index"],
                name="ajna_v1goer_pool_ad_4428e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipoolevent",
            index=models.Index(
                fields=["pool_address", "wallet_addresses"],
                name="ajna_v1goer_pool_ad_72cb86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipoolevent",
            index=models.Index(
                fields=["pool_address"], name="ajna_v1goer_pool_ad_984118_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipoolevent",
            index=models.Index(
                fields=["order_index"], name="ajna_v1goer_order_i_34d1ec_idx"
            ),
        ),
    ]
