# Generated by Django 4.2.3 on 2023-09-07 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0030_v2goerliwalletpoolposition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="v1ethereumpoolevent",
            name="pool_inflator",
        ),
        migrations.RemoveField(
            model_name="v1goerlipoolevent",
            name="pool_inflator",
        ),
        migrations.RemoveField(
            model_name="v2ethereumpoolevent",
            name="pool_inflator",
        ),
        migrations.RemoveField(
            model_name="v2goerlipoolevent",
            name="pool_inflator",
        ),
    ]
