# Generated by Django 4.2.3 on 2023-09-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0030_v1ethereumpoolevent_wallet_addresses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V1GoerliWalletPoolPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(db_index=True, max_length=42)),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("supply", models.DecimalField(decimal_places=18, max_digits=32)),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("t0debt", models.DecimalField(decimal_places=18, max_digits=32)),
                ("debt", models.DecimalField(decimal_places=18, max_digits=32)),
                ("datetime", models.DateTimeField()),
                ("block_number", models.BigIntegerField(db_index=True)),
            ],
            options={
                "ordering": ("block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
                "unique_together": {("wallet_address", "block_number", "pool_address")},
            },
        ),
        migrations.CreateModel(
            name="V1GoerliWalletPoolBucketState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=42)),
                ("pool_address", models.CharField(max_length=42)),
                ("bucket_index", models.IntegerField()),
                ("deposit", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=[
                            "pool_address",
                            "wallet_address",
                            "bucket_index",
                            "block_number",
                        ],
                        name="ajna_v1goer_pool_ad_647d13_idx",
                    ),
                    models.Index(
                        fields=["pool_address", "wallet_address", "bucket_index"],
                        name="ajna_v1goer_pool_ad_4e682a_idx",
                    ),
                    models.Index(
                        fields=["pool_address"], name="ajna_v1goer_pool_ad_ac4f38_idx"
                    ),
                    models.Index(
                        fields=["wallet_address"], name="ajna_v1goer_wallet__fdfce7_idx"
                    ),
                    models.Index(
                        fields=["bucket_index"], name="ajna_v1goer_bucket__575367_idx"
                    ),
                    models.Index(
                        fields=["block_number"], name="ajna_v1goer_block_n_8bb839_idx"
                    ),
                    models.Index(
                        fields=["block_datetime"], name="ajna_v1goer_block_d_10b3f9_idx"
                    ),
                ],
                "unique_together": {
                    ("pool_address", "wallet_address", "bucket_index", "block_number")
                },
            },
        ),
        migrations.CreateModel(
            name="V1GoerliPoolBucketState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(max_length=42)),
                ("bucket_index", models.IntegerField()),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("deposit", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["pool_address", "bucket_index", "block_number"],
                        name="ajna_v1goer_pool_ad_cb7e0e_idx",
                    ),
                    models.Index(
                        fields=["pool_address", "bucket_index"],
                        name="ajna_v1goer_pool_ad_24b501_idx",
                    ),
                    models.Index(
                        fields=["pool_address"], name="ajna_v1goer_pool_ad_24b3eb_idx"
                    ),
                    models.Index(
                        fields=["bucket_index"], name="ajna_v1goer_bucket__99b4f9_idx"
                    ),
                    models.Index(
                        fields=["block_number"], name="ajna_v1goer_block_n_91608c_idx"
                    ),
                    models.Index(
                        fields=["block_datetime"], name="ajna_v1goer_block_d_890566_idx"
                    ),
                ],
                "unique_together": {("pool_address", "bucket_index", "block_number")},
            },
        ),
        migrations.CreateModel(
            name="V1EthereumWalletPoolPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(db_index=True, max_length=42)),
                ("pool_address", models.CharField(db_index=True, max_length=42)),
                ("supply", models.DecimalField(decimal_places=18, max_digits=32)),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("t0debt", models.DecimalField(decimal_places=18, max_digits=32)),
                ("debt", models.DecimalField(decimal_places=18, max_digits=32)),
                ("datetime", models.DateTimeField()),
                ("block_number", models.BigIntegerField(db_index=True)),
            ],
            options={
                "ordering": ("block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
                "unique_together": {("wallet_address", "block_number", "pool_address")},
            },
        ),
        migrations.CreateModel(
            name="V1EthereumWalletPoolBucketState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=42)),
                ("pool_address", models.CharField(max_length=42)),
                ("bucket_index", models.IntegerField()),
                ("deposit", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=[
                            "pool_address",
                            "wallet_address",
                            "bucket_index",
                            "block_number",
                        ],
                        name="ajna_v1ethe_pool_ad_cb3ef1_idx",
                    ),
                    models.Index(
                        fields=["pool_address", "wallet_address", "bucket_index"],
                        name="ajna_v1ethe_pool_ad_f1e640_idx",
                    ),
                    models.Index(
                        fields=["pool_address"], name="ajna_v1ethe_pool_ad_da65ba_idx"
                    ),
                    models.Index(
                        fields=["wallet_address"], name="ajna_v1ethe_wallet__1c33e2_idx"
                    ),
                    models.Index(
                        fields=["bucket_index"], name="ajna_v1ethe_bucket__d3bd52_idx"
                    ),
                    models.Index(
                        fields=["block_number"], name="ajna_v1ethe_block_n_7afe86_idx"
                    ),
                    models.Index(
                        fields=["block_datetime"], name="ajna_v1ethe_block_d_4b2e4f_idx"
                    ),
                ],
                "unique_together": {
                    ("pool_address", "wallet_address", "bucket_index", "block_number")
                },
            },
        ),
        migrations.CreateModel(
            name="V1EthereumPoolBucketState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_address", models.CharField(max_length=42)),
                ("bucket_index", models.IntegerField()),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("deposit", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["pool_address", "bucket_index", "block_number"],
                        name="ajna_v1ethe_pool_ad_bfcfa1_idx",
                    ),
                    models.Index(
                        fields=["pool_address", "bucket_index"],
                        name="ajna_v1ethe_pool_ad_e5471d_idx",
                    ),
                    models.Index(
                        fields=["pool_address"], name="ajna_v1ethe_pool_ad_69b36f_idx"
                    ),
                    models.Index(
                        fields=["bucket_index"], name="ajna_v1ethe_bucket__061f52_idx"
                    ),
                    models.Index(
                        fields=["block_number"], name="ajna_v1ethe_block_n_050fa4_idx"
                    ),
                    models.Index(
                        fields=["block_datetime"], name="ajna_v1ethe_block_d_83bbdc_idx"
                    ),
                ],
                "unique_together": {("pool_address", "bucket_index", "block_number")},
            },
        ),
    ]
