# Generated by Django 4.2.3 on 2023-09-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0031_remove_v1ethereumpoolevent_pool_inflator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpoolbucketstate",
            name="bucket_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolbucketstate",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolbucketstate",
            name="lpb",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolbucketstate",
            name="bucket_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolbucketstate",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolbucketstate",
            name="lpb",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumpoolbucketstate",
            name="bucket_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumpoolbucketstate",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumpoolbucketstate",
            name="lpb",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlipoolbucketstate",
            name="bucket_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlipoolbucketstate",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlipoolbucketstate",
            name="lpb",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
