# Generated by Django 4.2.3 on 2023-09-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0033_delete_v2ethereumaddcollateral_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpoolevent",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpoolevent",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolevent",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipoolevent",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumpoolevent",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumpoolevent",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlipoolevent",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlipoolevent",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpricefeed",
            index=models.Index(
                fields=["underlying_address"], name="ajna_v1ethe_underly_7c1a97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpricefeed",
            index=models.Index(
                fields=["timestamp"], name="ajna_v1ethe_timesta_3be2e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpricefeed",
            index=models.Index(
                fields=["datetime"], name="ajna_v1ethe_datetim_aaddb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1ethereumpricefeed",
            index=models.Index(
                fields=["underlying_address", "datetime"],
                name="ajna_v1ethe_underly_286a90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipricefeed",
            index=models.Index(
                fields=["underlying_address"], name="ajna_v1goer_underly_adf5b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipricefeed",
            index=models.Index(
                fields=["timestamp"], name="ajna_v1goer_timesta_000d86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipricefeed",
            index=models.Index(
                fields=["datetime"], name="ajna_v1goer_datetim_51fbc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v1goerlipricefeed",
            index=models.Index(
                fields=["underlying_address", "datetime"],
                name="ajna_v1goer_underly_2bfd30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v2ethereumpricefeed",
            index=models.Index(
                fields=["underlying_address"], name="ajna_v2ethe_underly_7fd0c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v2ethereumpricefeed",
            index=models.Index(
                fields=["timestamp"], name="ajna_v2ethe_timesta_cdd3e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v2ethereumpricefeed",
            index=models.Index(
                fields=["datetime"], name="ajna_v2ethe_datetim_91d0fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v2ethereumpricefeed",
            index=models.Index(
                fields=["underlying_address", "datetime"],
                name="ajna_v2ethe_underly_694cff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v2goerlipricefeed",
            index=models.Index(
                fields=["underlying_address"], name="ajna_v2goer_underly_593e58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v2goerlipricefeed",
            index=models.Index(
                fields=["timestamp"], name="ajna_v2goer_timesta_607c24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v2goerlipricefeed",
            index=models.Index(
                fields=["datetime"], name="ajna_v2goer_datetim_a06214_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="v2goerlipricefeed",
            index=models.Index(
                fields=["underlying_address", "datetime"],
                name="ajna_v2goer_underly_14c750_idx",
            ),
        ),
    ]
