# Generated by Django 4.2.3 on 2023-10-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0038_alter_v2ethereumnotification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v2ethereumnotification",
            name="datetime",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="v2goerlinotification",
            name="datetime",
            field=models.DateTimeField(db_index=True),
        ),
    ]
