# Generated by Django 4.2.3 on 2023-10-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0039_alter_v2ethereumnotification_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v2ethereumnotification",
            name="pool_address",
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlinotification",
            name="pool_address",
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="v2ethereumnotification",
            unique_together={("pool_address", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="v2goerlinotification",
            unique_together={("pool_address", "key")},
        ),
    ]
