# Generated by Django 4.2.3 on 2023-09-28 08:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0039_alter_v2ethereumnotification_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpoolevent",
            name="bucket_indexes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="v1goerlipoolevent",
            name="bucket_indexes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="v2ethereumpoolevent",
            name="bucket_indexes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="v2goerlipoolevent",
            name="bucket_indexes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
    ]
