# Generated by Django 4.2.3 on 2023-10-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0040_v2ethereumnotification_pool_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v2ethereumnotification",
            name="key",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="v2goerlinotification",
            name="key",
            field=models.TextField(),
        ),
    ]
