# Generated by Django 4.2.3 on 2023-10-09 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0044_alter_v2ethereumauction_bond_factor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="V1EthereumGrantProposal",
        ),
        migrations.DeleteModel(
            name="V1GoerliGrantProposal",
        ),
        migrations.DeleteModel(
            name="V2EthereumGrantProposal",
        ),
        migrations.DeleteModel(
            name="V2GoerliGrantProposal",
        ),
    ]
