# Generated by Django 4.2.3 on 2023-10-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0045_delete_v1ethereumgrantproposal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V2EthereumGrantDistributionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("distribution_id", models.IntegerField(unique=True)),
                ("start_block", models.BigIntegerField()),
                ("end_block", models.BigIntegerField()),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2EthereumGrantEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("name", models.CharField(max_length=42)),
                ("data", models.JSONField()),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2EthereumGrantProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("proposal_id", models.TextField(unique=True)),
                ("distribution_id", models.IntegerField()),
                ("proposer", models.CharField(max_length=42)),
                ("description", models.TextField()),
                (
                    "total_tokens_requested",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("params", models.JSONField(null=True)),
                ("executed", models.BooleanField(default=False)),
                (
                    "screening_votes_received",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "funding_votes_received",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "funding_votes_positive",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "funding_votes_negative",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("funding_start_block_number", models.BigIntegerField()),
                ("finalize_start_block_number", models.BigIntegerField()),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2GoerliGrantDistributionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("distribution_id", models.IntegerField(unique=True)),
                ("start_block", models.BigIntegerField()),
                ("end_block", models.BigIntegerField()),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2GoerliGrantEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("name", models.CharField(max_length=42)),
                ("data", models.JSONField()),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2GoerliGrantProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("proposal_id", models.TextField(unique=True)),
                ("distribution_id", models.IntegerField()),
                ("proposer", models.CharField(max_length=42)),
                ("description", models.TextField()),
                (
                    "total_tokens_requested",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("params", models.JSONField(null=True)),
                ("executed", models.BooleanField(default=False)),
                (
                    "screening_votes_received",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "funding_votes_received",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "funding_votes_positive",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "funding_votes_negative",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("funding_start_block_number", models.BigIntegerField()),
                ("finalize_start_block_number", models.BigIntegerField()),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
    ]
