# Generated by Django 4.2.3 on 2023-10-09 09:56

import ajna.models.base
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0046_v2ethereumgrantdistributionperiod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v2ethereumgrantevent",
            name="data",
            field=models.JSONField(encoder=ajna.models.base._GrantEventDataJSONEncoder),
        ),
        migrations.AlterField(
            model_name="v2ethereumgrantproposal",
            name="funding_votes_negative",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumgrantproposal",
            name="funding_votes_positive",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumgrantproposal",
            name="funding_votes_received",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumgrantproposal",
            name="params",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="v2ethereumgrantproposal",
            name="screening_votes_received",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerligrantevent",
            name="data",
            field=models.JSONField(encoder=ajna.models.base._GrantEventDataJSONEncoder),
        ),
        migrations.AlterField(
            model_name="v2goerligrantproposal",
            name="funding_votes_negative",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerligrantproposal",
            name="funding_votes_positive",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerligrantproposal",
            name="funding_votes_received",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerligrantproposal",
            name="params",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="v2goerligrantproposal",
            name="screening_votes_received",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
