# Generated by Django 4.2.3 on 2023-10-10 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0047_alter_v2ethereumgrantevent_data_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="V2EthereumLiquidationAuction",
        ),
        migrations.DeleteModel(
            name="V2GoerliLiquidationAuction",
        ),
    ]
