# Generated by Django 4.2.3 on 2023-10-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0048_delete_v2ethereumliquidationauction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumwalletpoolposition",
            name="lup",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumwalletpoolposition",
            name="pending_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliwalletpoolposition",
            name="lup",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliwalletpoolposition",
            name="pending_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumwalletpoolposition",
            name="lup",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumwalletpoolposition",
            name="pending_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliwalletpoolposition",
            name="lup",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliwalletpoolposition",
            name="pending_inflator",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
