# Generated by Django 4.2.3 on 2023-10-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0051_v2ethereumauction_borrower_eoa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v2ethereumwallet",
            name="wallet_eoa",
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliwallet",
            name="wallet_eoa",
            field=models.CharField(max_length=42, null=True),
        ),
    ]
