# Generated by Django 4.2.3 on 2023-10-17 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0052_v2ethereumwallet_wallet_eoa_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="v2ethereumwallet",
            old_name="wallet_eoa",
            new_name="eoa",
        ),
        migrations.RenameField(
            model_name="v2goerliwallet",
            old_name="wallet_eoa",
            new_name="eoa",
        ),
    ]
