# Generated by Django 4.2.3 on 2023-10-17 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0053_rename_wallet_eoa_v2ethereumwallet_eoa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="v2ethereumauction",
            name="borrower_eoa",
        ),
        migrations.RemoveField(
            model_name="v2ethereumauction",
            name="kicker_eoa",
        ),
        migrations.RemoveField(
            model_name="v2goerliauction",
            name="borrower_eoa",
        ),
        migrations.RemoveField(
            model_name="v2goerliauction",
            name="kicker_eoa",
        ),
    ]
