# Generated by Django 4.2.3 on 2023-10-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0054_remove_v2ethereumauction_borrower_eoa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v2ethereumauctionauctionsettle",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionauctionsettle",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionbuckettake",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionbuckettake",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionkick",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionkick",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionsettle",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionsettle",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctiontake",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctiontake",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionauctionsettle",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionauctionsettle",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionbuckettake",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionbuckettake",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionkick",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionkick",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionsettle",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionsettle",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctiontake",
            name="collateral_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctiontake",
            name="quote_token_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
