# Generated by Django 4.2.3 on 2023-10-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0058_v1ethereumcurrentwalletpoolposition_in_liquidation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v1ethereumpool",
            name="address",
            field=models.CharField(db_index=True, max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipool",
            name="address",
            field=models.CharField(db_index=True, max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpool",
            name="address",
            field=models.CharField(db_index=True, max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipool",
            name="address",
            field=models.CharField(db_index=True, max_length=42, unique=True),
        ),
    ]
