# Generated by Django 4.2.3 on 2023-10-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0059_alter_v1ethereumpool_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V2EthereumReserveAuction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.TextField(unique=True)),
                ("pool_address", models.CharField(max_length=42)),
                (
                    "claimable_reserves",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "claimable_reserves_remaining",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "last_take_price",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("burn_epoch", models.BigIntegerField()),
                ("ajna_burned", models.DecimalField(decimal_places=18, max_digits=32)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2EthereumReserveAuctionKick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("reserve_auction_uid", models.TextField()),
                ("pool_address", models.CharField(max_length=42)),
                ("burn_epoch", models.BigIntegerField()),
                ("kicker", models.CharField(max_length=42)),
                ("kick_award", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "claimable_reserves",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "starting_price",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66)),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2EthereumReserveAuctionTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("reserve_auction_uid", models.TextField()),
                ("pool_address", models.CharField(max_length=42)),
                ("taker", models.CharField(max_length=42)),
                (
                    "claimable_reserves_remaining",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "auction_price",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("ajna_burned", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "quote_purchased",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66)),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2GoerliReserveAuction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.TextField(unique=True)),
                ("pool_address", models.CharField(max_length=42)),
                (
                    "claimable_reserves",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "claimable_reserves_remaining",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "last_take_price",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("burn_epoch", models.BigIntegerField()),
                ("ajna_burned", models.DecimalField(decimal_places=18, max_digits=32)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2GoerliReserveAuctionKick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("reserve_auction_uid", models.TextField()),
                ("pool_address", models.CharField(max_length=42)),
                ("burn_epoch", models.BigIntegerField()),
                ("kicker", models.CharField(max_length=42)),
                ("kick_award", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "claimable_reserves",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "starting_price",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66)),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2GoerliReserveAuctionTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("reserve_auction_uid", models.TextField()),
                ("pool_address", models.CharField(max_length=42)),
                ("taker", models.CharField(max_length=42)),
                (
                    "claimable_reserves_remaining",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                (
                    "auction_price",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("ajna_burned", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "quote_purchased",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66)),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
    ]
