# Generated by Django 4.2.3 on 2023-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ajna",
            "0061_rename_kick_award_v2ethereumreserveauctionkick_kicker_award_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpool",
            name="last_block_number",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="last_block_number",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumpool",
            name="last_block_number",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="v2goerlipool",
            name="last_block_number",
            field=models.BigIntegerField(null=True),
        ),
    ]
