# Generated by Django 4.2.3 on 2023-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0063_v3goerliauction_v3goerliauctionauctionsettle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V2EthereumAuctionAuctionNFTSettle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("auction_uid", models.TextField()),
                ("pool_address", models.CharField(max_length=42)),
                ("borrower", models.CharField(max_length=42)),
                ("index", models.TextField()),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66, null=True)),
                (
                    "collateral_token_price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
                (
                    "quote_token_price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="V2GoerliAuctionAuctionNFTSettle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("auction_uid", models.TextField()),
                ("pool_address", models.CharField(max_length=42)),
                ("borrower", models.CharField(max_length=42)),
                ("index", models.TextField()),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66, null=True)),
                (
                    "collateral_token_price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
                (
                    "quote_token_price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="v2ethereumauctionauctionsettle",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionbuckettake",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionkick",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctionsettle",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumauctiontake",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionauctionsettle",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionbuckettake",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionkick",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionsettle",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctiontake",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v3goerliauctionauctionsettle",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v3goerliauctionbuckettake",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v3goerliauctionkick",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v3goerliauctionsettle",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="v3goerliauctiontake",
            name="transaction_hash",
            field=models.CharField(max_length=66, null=True),
        ),
    ]
