# Generated by Django 4.2.3 on 2023-11-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0064_v2ethereumauctionauctionnftsettle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumcurrentwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumcurrentwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlicurrentwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlicurrentwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v1goerliwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumcurrentwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumcurrentwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlicurrentwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlicurrentwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v3goerlicurrentwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v3goerlicurrentwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v3goerliwalletpoolposition",
            name="npTpRatio",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v3goerliwalletpoolposition",
            name="t0Np",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
