# Generated by Django 4.2.3 on 2023-11-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ajna",
            "0066_rename_nptpratio_v1ethereumcurrentwalletpoolposition_np_tp_ratio_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="v1ethereumpool",
            name="collateral_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v1ethereumpool",
            name="quote_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="collateral_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v1goerlipool",
            name="quote_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumpool",
            name="collateral_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v2ethereumpool",
            name="quote_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlipool",
            name="collateral_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v2goerlipool",
            name="quote_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v3goerlipool",
            name="collateral_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="v3goerlipool",
            name="quote_token_symbol",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
