# Generated by Django 4.2.3 on 2023-11-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0067_alter_v1ethereumpool_momp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V3GoerliAuctionAuctionNFTSettle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.CharField(max_length=26, unique=True)),
                ("auction_uid", models.TextField()),
                ("pool_address", models.CharField(max_length=42)),
                ("borrower", models.CharField(max_length=42)),
                ("index", models.TextField()),
                ("collateral", models.DecimalField(decimal_places=18, max_digits=32)),
                ("block_number", models.BigIntegerField()),
                ("block_datetime", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=66, null=True)),
                (
                    "collateral_token_price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
                (
                    "quote_token_price",
                    models.DecimalField(decimal_places=18, max_digits=32, null=True),
                ),
            ],
            options={
                "ordering": ("-block_number",),
                "get_latest_by": "block_number",
                "abstract": False,
            },
        ),
    ]
