# Generated by Django 4.2.3 on 2023-11-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ajna",
            "0067_v1ethereumpool_collateral_token_symbol_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="v1ethereumpool",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1ethereumpoolsnapshot",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipool",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v1goerlipoolsnapshot",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpool",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpoolsnapshot",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipool",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipoolsnapshot",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v3goerlipool",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v3goerlipoolsnapshot",
            name="momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
