# Generated by Django 4.2.3 on 2023-11-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0069_v3goerliauctionauctionnftsettle"),
    ]

    operations = [
        migrations.AddField(
            model_name="v2ethereumauctionkick",
            name="reference_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v2goerliauctionkick",
            name="reference_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="v3goerliauctionkick",
            name="reference_price",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumauctionkick",
            name="kick_momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerliauctionkick",
            name="kick_momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name="v3goerliauctionkick",
            name="kick_momp",
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
