# Generated by Django 4.2.3 on 2024-01-10 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0078_alter_v1ethereumcurrentwalletpoolposition_debt_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="V3ArbitrumGrantDistributionPeriod",
        ),
        migrations.DeleteModel(
            name="V3ArbitrumGrantEvent",
        ),
        migrations.DeleteModel(
            name="V3ArbitrumGrantProposal",
        ),
        migrations.DeleteModel(
            name="V3BaseGrantDistributionPeriod",
        ),
        migrations.DeleteModel(
            name="V3BaseGrantEvent",
        ),
        migrations.DeleteModel(
            name="V3BaseGrantProposal",
        ),
        migrations.DeleteModel(
            name="V3OptimismGrantDistributionPeriod",
        ),
        migrations.DeleteModel(
            name="V3OptimismGrantEvent",
        ),
        migrations.DeleteModel(
            name="V3OptimismGrantProposal",
        ),
        migrations.DeleteModel(
            name="V3PolygonGrantDistributionPeriod",
        ),
        migrations.DeleteModel(
            name="V3PolygonGrantEvent",
        ),
        migrations.DeleteModel(
            name="V3PolygonGrantProposal",
        ),
    ]
