# Generated by Django 4.2.3 on 2024-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0080_v1ethereumpricefeed_estimated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V3NetworkStatsDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.CharField(db_index=True, max_length=42)),
                ("tvl", models.DecimalField(decimal_places=18, max_digits=32)),
                (
                    "collateral_usd",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("supply_usd", models.DecimalField(decimal_places=18, max_digits=32)),
                ("debt_usd", models.DecimalField(decimal_places=18, max_digits=32)),
                ("date", models.DateField()),
            ],
            options={
                "abstract": False,
                "unique_together": {("network", "date")},
            },
        ),
    ]
