# Generated by Django 4.2.3 on 2024-01-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0082_delete_v1ethereumaddcollateral_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v2ethereumpool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpool",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v2ethereumpoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v2ethereumpoolsnapshot",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v2goerlipool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipool",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v2goerlipoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v2goerlipoolsnapshot",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3arbitrumpool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3arbitrumpool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3arbitrumpool",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3arbitrumpoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3arbitrumpoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3arbitrumpoolsnapshot",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3basepool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3basepool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3basepool",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3basepoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3basepoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3basepoolsnapshot",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3ethereumpool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3ethereumpool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3ethereumpool",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3ethereumpoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3ethereumpoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3ethereumpoolsnapshot",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3goerlipool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3goerlipool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3goerlipool",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3goerlipoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3goerlipoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3goerlipoolsnapshot",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3optimismpool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3optimismpool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3optimismpool",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3optimismpoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3optimismpoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3optimismpoolsnapshot",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3polygonpool",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3polygonpool",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3polygonpool",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name="v3polygonpoolsnapshot",
            name="current_meaningful_utilization",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3polygonpoolsnapshot",
            name="lend_rate",
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="v3polygonpoolsnapshot",
            name="min_debt_amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
    ]
