# Generated by Django 4.2.3 on 2024-01-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0084_alter_v2ethereumpool_total_ajna_burned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V3OverallStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_ajna_burned",
                    models.DecimalField(decimal_places=18, max_digits=32),
                ),
                ("date", models.DateField(unique=True)),
            ],
            options={
                "ordering": ("-date",),
                "get_latest_by": "date",
                "abstract": False,
            },
        ),
    ]
