# Generated by Django 4.2.3 on 2024-01-23 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0086_v4arbitrumauction_v4arbitrumauctionauctionnftsettle_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="V2GoerliAuction",
        ),
        migrations.DeleteModel(
            name="V2GoerliAuctionAuctionNFTSettle",
        ),
        migrations.DeleteModel(
            name="V2GoerliAuctionAuctionSettle",
        ),
        migrations.DeleteModel(
            name="V2GoerliAuctionBucketTake",
        ),
        migrations.DeleteModel(
            name="V2GoerliAuctionKick",
        ),
        migrations.DeleteModel(
            name="V2GoerliAuctionSettle",
        ),
        migrations.DeleteModel(
            name="V2GoerliAuctionTake",
        ),
        migrations.DeleteModel(
            name="V2GoerliBucket",
        ),
        migrations.DeleteModel(
            name="V2GoerliCurrentWalletPoolPosition",
        ),
        migrations.DeleteModel(
            name="V2GoerliGrantDistributionPeriod",
        ),
        migrations.DeleteModel(
            name="V2GoerliGrantEvent",
        ),
        migrations.DeleteModel(
            name="V2GoerliGrantProposal",
        ),
        migrations.DeleteModel(
            name="V2GoerliNotification",
        ),
        migrations.DeleteModel(
            name="V2GoerliPool",
        ),
        migrations.DeleteModel(
            name="V2GoerliPoolBucketState",
        ),
        migrations.DeleteModel(
            name="V2GoerliPoolEvent",
        ),
        migrations.DeleteModel(
            name="V2GoerliPoolSnapshot",
        ),
        migrations.DeleteModel(
            name="V2GoerliPoolVolumeSnapshot",
        ),
        migrations.DeleteModel(
            name="V2GoerliPriceFeed",
        ),
        migrations.DeleteModel(
            name="V2GoerliReserveAuction",
        ),
        migrations.DeleteModel(
            name="V2GoerliReserveAuctionKick",
        ),
        migrations.DeleteModel(
            name="V2GoerliReserveAuctionTake",
        ),
        migrations.DeleteModel(
            name="V2GoerliToken",
        ),
        migrations.DeleteModel(
            name="V2GoerliWallet",
        ),
        migrations.DeleteModel(
            name="V2GoerliWalletPoolBucketState",
        ),
        migrations.DeleteModel(
            name="V2GoerliWalletPoolPosition",
        ),
    ]
