# Generated by Django 4.2.9 on 2024-03-08 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajna", "0089_v4gnosisauction_v4gnosisauctionauctionnftsettle_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="V3GoerliAuction",
        ),
        migrations.DeleteModel(
            name="V3GoerliAuctionAuctionNFTSettle",
        ),
        migrations.DeleteModel(
            name="V3GoerliAuctionAuctionSettle",
        ),
        migrations.DeleteModel(
            name="V3GoerliAuctionBucketTake",
        ),
        migrations.DeleteModel(
            name="V3GoerliAuctionKick",
        ),
        migrations.DeleteModel(
            name="V3GoerliAuctionSettle",
        ),
        migrations.DeleteModel(
            name="V3GoerliAuctionTake",
        ),
        migrations.DeleteModel(
            name="V3GoerliBucket",
        ),
        migrations.DeleteModel(
            name="V3GoerliCurrentWalletPoolPosition",
        ),
        migrations.DeleteModel(
            name="V3GoerliGrantDistributionPeriod",
        ),
        migrations.DeleteModel(
            name="V3GoerliGrantEvent",
        ),
        migrations.DeleteModel(
            name="V3GoerliGrantProposal",
        ),
        migrations.DeleteModel(
            name="V3GoerliNotification",
        ),
        migrations.DeleteModel(
            name="V3GoerliPool",
        ),
        migrations.DeleteModel(
            name="V3GoerliPoolBucketState",
        ),
        migrations.DeleteModel(
            name="V3GoerliPoolEvent",
        ),
        migrations.DeleteModel(
            name="V3GoerliPoolSnapshot",
        ),
        migrations.DeleteModel(
            name="V3GoerliPoolVolumeSnapshot",
        ),
        migrations.DeleteModel(
            name="V3GoerliPriceFeed",
        ),
        migrations.DeleteModel(
            name="V3GoerliReserveAuction",
        ),
        migrations.DeleteModel(
            name="V3GoerliReserveAuctionKick",
        ),
        migrations.DeleteModel(
            name="V3GoerliReserveAuctionTake",
        ),
        migrations.DeleteModel(
            name="V3GoerliToken",
        ),
        migrations.DeleteModel(
            name="V3GoerliWallet",
        ),
        migrations.DeleteModel(
            name="V3GoerliWalletPoolBucketState",
        ),
        migrations.DeleteModel(
            name="V3GoerliWalletPoolPosition",
        ),
    ]
