# Generated by Django 5.0.6 on 2024-05-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajna', '0092_v2ethereumpoolsnapshot_ajna_v2ethe_address_e10b82_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='V4ArbitrumActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_wallets', models.IntegerField()),
                ('total_wallets', models.IntegerField()),
                ('new_wallets', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V4BaseActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_wallets', models.IntegerField()),
                ('total_wallets', models.IntegerField()),
                ('new_wallets', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V4BlastActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_wallets', models.IntegerField()),
                ('total_wallets', models.IntegerField()),
                ('new_wallets', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V4EthereumActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_wallets', models.IntegerField()),
                ('total_wallets', models.IntegerField()),
                ('new_wallets', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V4GnosisActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_wallets', models.IntegerField()),
                ('total_wallets', models.IntegerField()),
                ('new_wallets', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V4ModeActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_wallets', models.IntegerField()),
                ('total_wallets', models.IntegerField()),
                ('new_wallets', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V4OptimismActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_wallets', models.IntegerField()),
                ('total_wallets', models.IntegerField()),
                ('new_wallets', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V4PolygonActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_wallets', models.IntegerField()),
                ('total_wallets', models.IntegerField()),
                ('new_wallets', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
