# Generated by Django 5.0.6 on 2024-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajna', '0093_v4arbitrumactivitysnapshot_v4baseactivitysnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='v4arbitrumactivitysnapshot',
            name='active_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4baseactivitysnapshot',
            name='active_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4blastactivitysnapshot',
            name='active_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4ethereumactivitysnapshot',
            name='active_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4gnosisactivitysnapshot',
            name='active_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4modeactivitysnapshot',
            name='active_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4optimismactivitysnapshot',
            name='active_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4polygonactivitysnapshot',
            name='active_this_month',
            field=models.IntegerField(null=True),
        ),
    ]
