# Generated by Django 5.0.6 on 2024-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajna', '0094_v4arbitrumactivitysnapshot_active_this_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='v4arbitrumactivitysnapshot',
            name='new_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4baseactivitysnapshot',
            name='new_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4blastactivitysnapshot',
            name='new_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4ethereumactivitysnapshot',
            name='new_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4gnosisactivitysnapshot',
            name='new_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4modeactivitysnapshot',
            name='new_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4optimismactivitysnapshot',
            name='new_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='v4polygonactivitysnapshot',
            name='new_this_month',
            field=models.IntegerField(null=True),
        ),
    ]
