# Generated by Django 5.0.6 on 2024-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajna', '0095_v4arbitrumactivitysnapshot_new_this_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='v2ethereumreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v3arbitrumreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v3basereserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v3ethereumreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v3optimismreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v3polygonreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v4arbitrumreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v4basereserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v4blastreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v4gnosisreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v4modereserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v4optimismreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='v4polygonreserveauctiontake',
            name='ajna_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
