# Generated by Django 5.0.6 on 2024-08-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajna', '0096_v2ethereumreserveauctiontake_ajna_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v2ethereumreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v2ethereumreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3arbitrumreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3arbitrumreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3basereserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3basereserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3ethereumreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3ethereumreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3optimismreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3optimismreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3polygonreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v3polygonreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4arbitrumreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4arbitrumreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4basereserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4basereserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4blastreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4blastreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4gnosisreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4gnosisreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4modereserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4modereserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4optimismreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4optimismreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4polygonreserveauctionkick',
            name='claimable_reserves',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
        migrations.AlterField(
            model_name='v4polygonreserveauctionkick',
            name='starting_price',
            field=models.DecimalField(decimal_places=18, max_digits=64),
        ),
    ]
