name: "setup-uv-env"
description: "Composite action to setup the UV environment."

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
        enable-cache: true
    - name: Install the project
      run: uv sync --dev
      shell: bash
